### ISSUE TITLE
Webhook kodunu kaçıncı satıra yazacağım

### ISSUE THREAD

**Issue by Emre1337q** [selim1337/discord-keylogger#1]
Webhook kodunu kaçıncı satıra yazacağım

**Comment by selim1337** [comment]
Selam dostum webhook kodunu 7. satıra yazacaksın bir bu kadar hızlı bir sorun beklemiyordum :) iyi günler discorddan da ulaşabilirsin

**Comment by Emre1337q** [comment]
Anladım teşekkür ederim
